### PR TITLE
Rename isSecurityCodeValid to isCVVValid

### LINKED ISSUE #70: Rename isSecurityCodeValid in 1.1
@remear pointed out that the `csc` field has been renamed to card verification value (`cvv`) and as such we should change the method to `isCardVerificationValueValid` or `isCVVValid`

### PR DESCRIPTION
**Pull request by remear**
Fixes https://github.com/balanced/balanced-js/issues/70

### CODE REVIEW

**Comment by mjallday** [comment]
@remear i almost forgot that this is a breaking change. we should alias the old command to this until we have a chance to update any users of this feature and #75 too.

**Comment by matthewfl** [comment]
this is just going out on rev1 right? so there should not be any real problems with this breaking change right?

**Comment by mjallday** [comment]
The dashboard would break until we deployed a new version since it's [pegged at the minor version](https://github.com/balanced/balanced-dashboard/blob/82d00834bb655b374b23cb4040c731f12400cfec/app/index.html.hbs#L21), not the build.

**Comment by matthewfl** [comment]
I think it would be easier then to just deploy both of these updates at the same, while that is not as "clean" I feel that is better then having soon to be dead code in balanced.js

**Pull request merged**
