### PR TITLE
Add support for JCB and Diners Club cards.

### PR DESCRIPTION
**Pull request by zachsnow**
According to the [documentation](https://support.balancedpayments.com/hc/en-us/articles/200319895-Does-Balanced-accept-JCB-and-Diners-Club-cards) Balanced supports JCB and Diners, but they weren't recognized by balanced-js. I added support for their prefixes based on Wikipedia. Also added test card numbers found elsewhere online; these should be changed if there are specific numbers you support.

-Zach

### CODE REVIEW

**Comment by matthewfl** [comment]
this looks good to me, but are you using rev1 of the api?

**Comment by zachsnow** [comment]
I pulled the branch off of `rev1`, if that is what you are asking?

**Comment by zachsnow** [comment]
Thanks from fareharbor.com!

**Comment by mjallday** [comment]
@matthewfl do you have the power to bump the version and deploy?

@zachsnow shoot us an email to support@balancedpayments.com if you'd like some swag for helping us improve the library.

**Comment by matthewfl** [comment]
this is live on rev0 and rev1

https://js.balancedpayments.com/v1/balanced.js
https://js.balancedpayments.com/balanced.js

**Pull request merged**
