### PR TITLE
refactor(balanced.js): helpers, devDependencies

### PR DESCRIPTION
**Pull request by PatrickJS**
The repo is currently broken for web users

### CODE REVIEW

**Comment by mahmoudimus** [comment]
Hey @gdi2290 thanks for this! ping @cohitre can you take a look at this?

**Comment by PatrickJS** [comment]
I update the PR to pass the test. I had a UMD setup until I noticed there was a build step that wasn't committed. I updated the <code>.gitignore</code> to include the build files and added <code>bower.json</code>. There was also a problem with your package.json for node users

**Comment by Hendrixer** [comment]
I'm having this same issue too.

**Comment by MehulATL** [comment]
:+1:

**Comment by mjallday** [comment]
i think the `build` dir should be excluded from source control.

**Comment by PatrickJS** [comment]
I agree but this library is broken for bower and I can't create a better build system without repo rights so this is good enough to get the ball rolling

**Comment by PatrickJS** [comment]
gg

**Pull request closed without merging**
