### PR TITLE
fixing faked error messages to match the array format

### PR DESCRIPTION
**Pull request by matthewfl**

### CODE REVIEW

**Comment by mjallday** [comment]
This appears to be consistently failing the build due to some broked dependency.

**Comment by matthewfl** [comment]
looks like me removing that item from package.json had nothing to do with it.

the build is now failing on master as well https://travis-ci.org/balanced/balanced-js/builds/19833298

**Comment by mjallday** [comment]
Please bump the minor version number before deploying.

**Comment by matthewfl** [comment]
why would you merge and not deploy????????????????????

```
            ________
        _jgN########Ngg_
      _N##N@@""  ""9NN##Np_
     d###P            N####p
     "^^"              T####
                       d###P
                    _g###@F
                 _gN##@P
               gN###F"
              d###F
             0###F
             0###F
             0###F
             "NN@'

              ___
             q###r
```

**Pull request merged**
