### PR TITLE
Jsonp

### PR DESCRIPTION
**Pull request by matthewfl**
this adds support for rev1, and uses jsonp to make cross domain requests to api.balancedpayments.com/jsonp/(cards|bank_accounts).

There is currently no support for rev0 tokenizations with a marketplace id

### CODE REVIEW

**Comment by mjallday** [comment]
this is pretty cool looking, a definite win. it's going to block until #26 is implemented so that we don't accidentally refactor out any required functionality.

**Comment by mjallday** [comment]
I think for a deployment strategy this would be deployed as an entirely new file. no need to maintain backwards compatibility with rev0

**Comment by sgalbrai** [comment]
We need this at Ribbon.co.  We also need crossdomain.xml support.

**Comment by mjallday** [comment]
@sgalbrai i believe this jsonp change will suffice for Flash. e.g. https://gist.github.com/sfsekaran/1793867

**Comment by sgalbrai** [comment]
I implemented this exactly... Doesn't work.

**Comment by mjallday** [comment]
@sgalbrai yes, that's because this change hasn't been deployed yet. what i meant was this _will_ work _after_ it has been deployed :)

**Comment by sgalbrai** [comment]
My problem is different, I get a local security exception (thrown by
Flash).  It cannot create the <script> object in the third-party parent
HTML container due to document.domain restrictions that I cannot change or
edit.  The only solution is for Balanced to allow CORs from Flash through a
crossdomain.xml file. That way my flash code can make the remote data
request without throwing a security exception.

**Comment by nodesocket** [comment]
Crossdomain.xml should be serving now:

https://api.balancedpayments.com/crossdomain.xml

**Pull request closed without merging**
